### ISSUE TITLE
Please add license headers to library files

### ISSUE THREAD

**Issue by grigorig** [saewave/STM32F103-USB-CDC-CMSIS#1]
The title says it all. This would clarify the licensing situation when files are integrated into a different project.

I'd also love a change to a permissive license, but that's just me. What do you think?

**Comment by saewave** [comment]
Thanks for your notice.
I've added GPL v3 header to files.
Which license you prefer to have?

**Comment by grigorig** [comment]
Thanks for adding the headers!

GPL licenses have various incompatibilities. For instance, GPLv3 is incompatible to GPLv2 and several other licenses. So if you put aside any fears about corporate users of the code that don't want to give back anything, it might be a good idea to switch to a more permissive license. I don't want to start a license politics discussion though...

Both the MIT license or the LGPL license would possibly make your code much more useful, even if it is going to be used in other Open Source projects.

**Comment by saewave** [comment]
My main goal is that developers who using my code in their projects should open his code to make contribution in open-source community.
I believe that corporations and business, who build a commercial project can develop their own versions  or contact me to ask about using my code in their projects.
MIT and JGPL is not acceptable for my vision.
